"""Preserve the supplied embedded PNG for self-contained battle SVGs."""
import base64
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
kind = sys.argv[2] if len(sys.argv) > 2 else 'halberd'
if kind not in ('halberd', 'shield'):
    raise ValueError('Knight kind must be halberd or shield')
source = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'assets/knight-original.svg'
svg = ET.parse(source).getroot()
image = svg.find('{http://www.w3.org/2000/svg}image')
uri = image.get('href', '') if image is not None else ''
if not uri.startswith('data:image/png;base64,'):
    raise ValueError('Expected the supplied self-contained PNG image')
png = base64.b64decode(uri.split(',', 1)[1], validate=True)
if png[:8] != b'\x89PNG\r\n\x1a\n':
    raise ValueError('Invalid PNG signature')
width, height = (int.from_bytes(png[i:i+4], 'big') for i in (16, 20))
output = '// Generated by tools/prepare-knight.py; supplied artwork preserved unchanged.\n'
prefix = 'SHIELD_KNIGHT' if kind == 'shield' else 'KNIGHT'
output += f'export const {prefix}_WIDTH = {width};\nexport const {prefix}_HEIGHT = {height};\n'
output += f'export const {prefix}_IMAGE = {json.dumps(uri)};\n'
(root / ('shield-knight-source.mjs' if kind == 'shield' else 'knight-source.mjs')).write_text(output)
