"""Split the supplied 96x96 vector shield knight into lossless pixel animation layers."""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from xml.etree import ElementTree as ET

root = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'assets/shield-knight-original.svg'
raw = source.read_bytes()
svg = ET.fromstring(raw)
if svg.get('viewBox') != '0 0 96 96':
    raise ValueError('Expected a 96x96 pixel sprite')
cells = {}
for e in svg.iter():
    tag = e.tag.split('}')[-1]
    if e.get('transform'):
        raise ValueError('Transformed pixels are unsupported')
    if tag in ('svg', 'g'):
        continue
    if tag != 'rect' or e.get('width') != '1' or e.get('height') != '1':
        raise ValueError('Only 1x1 vector pixels are supported')
    x, y = int(e.get('x')), int(e.get('y'))
    color = e.get('fill', '')
    if not (0 <= x < 96 and 0 <= y < 96) or not re.fullmatch(r'#[0-9a-fA-F]{6}', color):
        raise ValueError('Invalid pixel')
    if (x, y) in cells:
        raise ValueError('Overlapping pixels')
    cells[x, y] = color


def inside(x, y, polygon):
    x, y = x + .5, y + .5
    hit = False
    for (ax, ay), (bx, by) in zip(polygon, polygon[1:] + polygon[:1]):
        if (ay > y) != (by > y) and x < (bx-ax)*(y-ay)/(by-ay)+ax:
            hit = not hit
    return hit


def layer(x, y):
    if inside(x, y, [(20,26),(25,24),(30,19),(34,19),(38,23),(47,28),(49,31),(49,59),(47,67),(43,73),(41,74),(37,70),(30,61),(26,53),(23,44),(21,37)]):
        return 'shield'
    if y >= 62 and x < 41:
        return 'frontLeg'
    if y >= 62 and x >= 55:
        return 'backLeg'
    return 'body'


def paths(pixels):
    colors = defaultdict(list)
    for y in range(96):
        x = 0
        while x < 96:
            color = pixels.get((x, y))
            if color is None:
                x += 1
                continue
            start = x
            x += 1
            while x < 96 and pixels.get((x, y)) == color:
                x += 1
            colors[color].append(f'M{start} {y}h{x-start}v1h-{x-start}z')
    return ''.join(f'<path fill="{c}" d="{"".join(runs)}"/>' for c, runs in colors.items())

parts = {name: {} for name in ('frontLeg', 'backLeg', 'body', 'shield')}
for pos, color in cells.items():
    parts[layer(*pos)][pos] = color
assert sum(map(len, parts.values())) == len(cells)
markup = {name: paths(pixels) for name, pixels in parts.items()}
joints = {pos: color for pos, color in cells.items()
          if (layer(*pos) in ('frontLeg','backLeg') and pos[1] < 65)
          or (layer(*pos) == 'shield' and pos[0] >= 46 and 33 <= pos[1] <= 60)}
edge = {pos: '#edceff' for pos, color in parts['shield'].items()
        if min(int(color[i:i+2], 16) for i in (1,3,5)) > 155}
halo = {}
for x, y in edge:
    for dy in range(-3, 4):
        for dx in range(-3, 4):
            distance = abs(dx) + abs(dy)
            if distance <= 3 and 0 <= x+dx < 96 and 0 <= y+dy < 96:
                pos = (x+dx, y+dy)
                halo[pos] = min(distance, halo.get(pos, 4))
halo_markup = ''.join('<g opacity="' + opacity + '">' + paths({pos: '#cc88ff' for pos, d in halo.items() if d == distance}) + '</g>'
                      for distance, opacity in [(3,'.35'), (2,'.65'), (1,'.9'), (0,'1')])
(root / 'assets/shield-knight-original.svg').write_bytes(raw)
(root / 'assets/shield-knight.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" shape-rendering="crispEdges">' + ''.join(markup.values()) + '</svg>\n')
(root / 'shield-knight-source.mjs').write_text('// Generated by tools/prepare-knight.py; lossless vector pixel layers.\nexport const SHIELD_LAYERS = ' + json.dumps(markup) + ';\nexport const SHIELD_JOINTS = ' + json.dumps(paths(joints)) + ';\nexport const SHIELD_EDGE = ' + json.dumps(paths(edge)) + ';\nexport const SHIELD_HALO = ' + json.dumps(halo_markup) + ';\n')
print(f'Preserved {len(cells)} vector pixels in {len(parts)} animation layers.')
