"""Convert the licensed IM Fell font into reusable SVG glyph paths.
Build-time dependency only: python3 -m pip install fonttools==4.66.1
Runtime and GitHub Actions use the committed JS data; they never load a font.
"""
from pathlib import Path
import hashlib
import json
import string
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

root = Path(__file__).resolve().parents[1]
source = root / 'fonts/IMFePIrm28P.ttf'
font = TTFont(source)
cmap = font.getBestCmap()
glyph_set = font.getGlyphSet()
characters = string.ascii_uppercase + string.digits + ' :/.-·'
bounds = BoundsPen(glyph_set)
glyph_set[cmap[ord('H')]].draw(bounds)
cap_height = bounds.bounds[3]
glyphs = {}
for char in characters:
    name = cmap[ord(char)]
    pen = SVGPathPen(glyph_set, ntos=lambda n: f'{n:.2f}'.rstrip('0').rstrip('.') if '.' in f'{n:.2f}' else str(n))
    if char.isdigit():
        # Align old-style figures to a common cap height for small game counters.
        box = BoundsPen(glyph_set)
        glyph_set[name].draw(box)
        bottom, top = box.bounds[1], box.bounds[3]
        vertical = cap_height / (top-bottom)
        glyph_set[name].draw(TransformPen(pen, (1,0,0,vertical,0,-bottom*vertical)))
    else:
        glyph_set[name].draw(pen)
    glyphs[char] = {'advance': font['hmtx'][name][0], 'path': pen.getCommands()}
# The font lacks these two UI symbols. Keep them explicit original SVG shapes.
glyphs['−'] = {'advance': 1100, 'path': 'M150 570H950V680H150Z'}
glyphs['✓'] = {'advance': 1400, 'path': 'M130 580L440 180L1290 1120L1170 1240L450 450L250 700Z'}
kern = {}
for table in font['kern'].kernTables:
    for left in characters:
        for right in characters:
            value = table.kernTable.get((cmap[ord(left)], cmap[ord(right)]), 0)
            if value:
                kern[left+right] = value
output = '// Generated by tools/prepare-font.py. IM Fell DW Pica, Igino Marini; SIL OFL 1.1 (fonts/OFL.txt).\n'
output += 'export const FONT = ' + json.dumps({'name':'IM Fell DW Pica', 'sha256':hashlib.sha256(source.read_bytes()).hexdigest(), 'capHeight':cap_height, 'glyphs':glyphs, 'kerning':kern}, separators=(',',':')) + ';\n'
(root / 'font-source.mjs').write_text(output)
print(f'Generated {len(glyphs)} reusable glyphs ({len(output):,} bytes).')
